// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sender/v1beta/packets.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/tendermint/tendermint/abci/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorUpdatesPacketData struct {
	ValidatorsCommit []byte                   `protobuf:"bytes,1,opt,name=validators_commit,json=validatorsCommit,proto3" json:"validators_commit,omitempty"`
	ValidatorUpdates []*types.ValidatorUpdate `protobuf:"bytes,2,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates,omitempty"`
}

func (m *ValidatorUpdatesPacketData) Reset()         { *m = ValidatorUpdatesPacketData{} }
func (m *ValidatorUpdatesPacketData) String() string { return proto.CompactTextString(m) }
func (*ValidatorUpdatesPacketData) ProtoMessage()    {}
func (*ValidatorUpdatesPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33f01fc8e155314, []int{0}
}
func (m *ValidatorUpdatesPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorUpdatesPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorUpdatesPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorUpdatesPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorUpdatesPacketData.Merge(m, src)
}
func (m *ValidatorUpdatesPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorUpdatesPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorUpdatesPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorUpdatesPacketData proto.InternalMessageInfo

func (m *ValidatorUpdatesPacketData) GetValidatorsCommit() []byte {
	if m != nil {
		return m.ValidatorsCommit
	}
	return nil
}

func (m *ValidatorUpdatesPacketData) GetValidatorUpdates() []*types.ValidatorUpdate {
	if m != nil {
		return m.ValidatorUpdates
	}
	return nil
}

type SyncEntry struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *SyncEntry) Reset()         { *m = SyncEntry{} }
func (m *SyncEntry) String() string { return proto.CompactTextString(m) }
func (*SyncEntry) ProtoMessage()    {}
func (*SyncEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33f01fc8e155314, []int{1}
}
func (m *SyncEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncEntry.Merge(m, src)
}
func (m *SyncEntry) XXX_Size() int {
	return m.Size()
}
func (m *SyncEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SyncEntry proto.InternalMessageInfo

func (m *SyncEntry) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *SyncEntry) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func init() {
	proto.RegisterType((*ValidatorUpdatesPacketData)(nil), "hackatomibcapp.sender.v1beta1.ValidatorUpdatesPacketData")
	proto.RegisterType((*SyncEntry)(nil), "hackatomibcapp.sender.v1beta1.SyncEntry")
}

func init() { proto.RegisterFile("sender/v1beta/packets.proto", fileDescriptor_a33f01fc8e155314) }

var fileDescriptor_a33f01fc8e155314 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0x42, 0x41,
	0x18, 0xc5, 0xbd, 0x06, 0x86, 0x53, 0x8b, 0xba, 0x9b, 0x44, 0x71, 0x10, 0x57, 0x42, 0x38, 0x83,
	0xf6, 0x06, 0x59, 0x0b, 0xa1, 0x20, 0x8c, 0x5a, 0xb4, 0x91, 0x6f, 0xfe, 0x90, 0x83, 0xce, 0x1f,
	0xee, 0xfd, 0x94, 0x7c, 0x8b, 0x96, 0x3d, 0x52, 0x4b, 0x97, 0x2d, 0x43, 0x5f, 0x24, 0x1c, 0xaf,
	0x28, 0x2d, 0xbf, 0x73, 0xce, 0x9c, 0x39, 0xfc, 0x48, 0x23, 0xd7, 0x4e, 0xe9, 0x8c, 0x2f, 0x7a,
	0x42, 0x23, 0xf0, 0x00, 0x72, 0xaa, 0x31, 0x67, 0x21, 0xf3, 0xe8, 0xd3, 0xe6, 0x04, 0xe4, 0x14,
	0xd0, 0x5b, 0x23, 0x24, 0x84, 0xc0, 0x76, 0x59, 0xb6, 0xcb, 0xf6, 0xea, 0x0d, 0x8c, 0xb7, 0x35,
	0x0e, 0x39, 0x08, 0x69, 0x38, 0x2e, 0x83, 0x2e, 0xde, 0xb6, 0xbf, 0x12, 0x52, 0x7f, 0x85, 0x99,
	0x51, 0x80, 0x3e, 0x7b, 0x09, 0x0a, 0x50, 0xe7, 0x4f, 0xb1, 0xfd, 0x0e, 0x10, 0xd2, 0x6b, 0x72,
	0xb9, 0xd8, 0xbb, 0xf9, 0x58, 0x7a, 0x6b, 0x0d, 0xd6, 0x92, 0x56, 0xd2, 0x39, 0x1f, 0x5d, 0x1c,
	0x8c, 0x41, 0xd4, 0xd3, 0xc7, 0xa3, 0xf0, 0x78, 0xbe, 0xeb, 0xaa, 0x95, 0x5b, 0x27, 0x9d, 0xb3,
	0x7e, 0x8b, 0x1d, 0x46, 0xb0, 0xed, 0x08, 0xf6, 0xef, 0xd3, 0xa3, 0xba, 0x62, 0x45, 0x7b, 0x40,
	0xaa, 0xcf, 0x4b, 0x27, 0xef, 0x1d, 0x66, 0xcb, 0xb4, 0x49, 0x88, 0x9c, 0x80, 0x73, 0x7a, 0x36,
	0x36, 0x2a, 0x2e, 0xa8, 0x8e, 0xaa, 0x85, 0x32, 0x54, 0xe9, 0x15, 0x39, 0x0d, 0x3e, 0xc3, 0xad,
	0x57, 0x8e, 0x5e, 0x65, 0x7b, 0x0e, 0xd5, 0xed, 0xc3, 0xf7, 0x9a, 0x26, 0xab, 0x35, 0x4d, 0x7e,
	0xd7, 0x34, 0xf9, 0xdc, 0xd0, 0xd2, 0x6a, 0x43, 0x4b, 0x3f, 0x1b, 0x5a, 0x7a, 0xeb, 0xbf, 0x1b,
	0x9c, 0xcc, 0x05, 0x93, 0xde, 0x72, 0x2b, 0xbd, 0x93, 0x80, 0x7c, 0x0f, 0xb2, 0x6b, 0x84, 0xec,
	0x42, 0x08, 0xfc, 0x83, 0x17, 0xe0, 0x23, 0x33, 0x51, 0x89, 0xd0, 0x6e, 0xfe, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0xcd, 0xef, 0x0d, 0x8f, 0x01, 0x00, 0x00,
}

func (m *ValidatorUpdatesPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorUpdatesPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorUpdatesPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorUpdates) > 0 {
		for iNdEx := len(m.ValidatorUpdates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorUpdates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPackets(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ValidatorsCommit) > 0 {
		i -= len(m.ValidatorsCommit)
		copy(dAtA[i:], m.ValidatorsCommit)
		i = encodeVarintPackets(dAtA, i, uint64(len(m.ValidatorsCommit)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SyncEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintPackets(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintPackets(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPackets(dAtA []byte, offset int, v uint64) int {
	offset -= sovPackets(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorUpdatesPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorsCommit)
	if l > 0 {
		n += 1 + l + sovPackets(uint64(l))
	}
	if len(m.ValidatorUpdates) > 0 {
		for _, e := range m.ValidatorUpdates {
			l = e.Size()
			n += 1 + l + sovPackets(uint64(l))
		}
	}
	return n
}

func (m *SyncEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovPackets(uint64(l))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovPackets(uint64(l))
	}
	return n
}

func sovPackets(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPackets(x uint64) (n int) {
	return sovPackets(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorUpdatesPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPackets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorUpdatesPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorUpdatesPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsCommit", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPackets
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPackets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorsCommit = append(m.ValidatorsCommit[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorsCommit == nil {
				m.ValidatorsCommit = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorUpdates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPackets
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPackets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorUpdates = append(m.ValidatorUpdates, &types.ValidatorUpdate{})
			if err := m.ValidatorUpdates[len(m.ValidatorUpdates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPackets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPackets
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPackets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPackets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPackets
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPackets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPackets
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPackets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPackets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPackets
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPackets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPackets(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPackets
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPackets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPackets
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPackets
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPackets
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPackets        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPackets          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPackets = fmt.Errorf("proto: unexpected end of group")
)
